### ISSUE TITLE
Optimization potential?

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/gdal-tiling-bench#27]
/cc @springmeyer @mapsam 

Looking into speeding up tiff uploads I used a new tool from Microsoft ([Concurrency Visualizer](https://msdn.microsoft.com/en-us/library/ee329530.aspx)) and ran `benchall` with 2 tiffs and 1 `node-mapnik` version (latest changes from master (exec) are not yet carried over to [my branch](https://github.com/mapbox/node-mapnik-bench/compare/extend-benchall?diff=split&name=extend-benchall)).

I think it's interesting that **84%** of the time are spent with `synchronisation` and only **16%** with `execution`.

Also, there seem to be **7 threads** that don't to anything at all.

I think, I'm going to dig a bit deeper here and see if there is an easy way to increase parallelization and decrease time spent with `synchronisation`.  

![image](https://cloud.githubusercontent.com/assets/4549888/14756652/fff24722-089f-11e6-8da1-bb1b61ff1dea.png)

**Comment by springmeyer** [comment]
@BergWerkGIS interesting. Is this with node v0.10.x or v4.x? I'm asking because I recall discovering - in Berlin - with you that node v0.10.x did not limit the number of threads (just on windows) and too many were created. Whereas in node >- v0.12.x this was fixed and the size of the thread pool respected the `UV_THREADPOOL_SIZE`.

**Comment by wilhelmberg** [comment]
```
λ node -v
v4.2.1
```

**Comment by springmeyer** [comment]
Okay, thanks so it not runaway threads: good. So my next hunch is that it is GDAL synchronization in the GDAL block cache. This is going to be hitting windows hard because GDAL does not support GTIFF_VIRTUAL_MEM_IO on windows. On Linux when GTIFF_VIRTUAL_MEM_IO is enabled it disables the block cache and disables the need for locking around the block cache.

**Comment by wilhelmberg** [comment]
Alright, nothing to optimize then.
